# Generated by Django 3.2.9 on 2022-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheppy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='timeout',
            field=models.IntegerField(default=1),
        ),
    ]
